//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Citas()
        {
            this.Facturas = new HashSet<Facturas>();
        }
    
        public int Id_Cita { get; set; }
        public System.DateTime Fecha_Cita { get; set; }
        public System.TimeSpan Hora_Cita { get; set; }
        public int Id_Usuario { get; set; }
        public int Id_Servicio { get; set; }
        public int Id_Empleado { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Servicios Servicios { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas> Facturas { get; set; }
    }
}
