//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Ganancias_Facturas
    {
        public int Id_Factura_Ganancias { get; set; }
        public int Id_Factura { get; set; }
        public int Id_Ganancia { get; set; }
    
        public virtual Facturas Facturas { get; set; }
        public virtual GananciaDiaria GananciaDiaria { get; set; }
    }
}
