//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenesServicios
    {
        public int Id_Foto_Servicio { get; set; }
        public int Id_Servicio { get; set; }
        public byte[] Foto_Servicio { get; set; }
        public string Nombre_Foto { get; set; }
    
        public virtual Servicios Servicios { get; set; }
    }
}
