//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenesProductos
    {
        public int Id_Foto_Producto { get; set; }
        public int Id_Producto { get; set; }
        public byte[] Foto_Producto { get; set; }
        public string Nombre_Foto_Producto { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
