//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromocionesProductos
    {
        public int Id_Promo_Producto { get; set; }
        public string Nombre_Promo_Producto { get; set; }
        public string Descripcion_Promo_Producto { get; set; }
        public decimal Precio_Nuevo_Producto { get; set; }
        public System.DateTime Fecha_Inicio_Promo { get; set; }
        public System.DateTime Fecha_Final_Promo { get; set; }
        public int Id_Producto { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
